### ISSUE TITLE
Error in the generated bootloader.h made by the Makefile

### ISSUE THREAD

**Issue by tobiola** [mihaigalos/miniboot#3] opened 2018-03-21 23:15 UTC
pi@raspberrypi:~/XX-Core/arduino/miniboot/src $ make rebuild

-------- start --------

Cleaning project:
rm -f miniboot.hex
rm -f miniboot.eep
rm -f miniboot.obj
rm -f miniboot.cof
rm -f miniboot.elf
rm -f miniboot.map
rm -f miniboot.obj
rm -f miniboot.a90
rm -f miniboot.sym
rm -f miniboot.lnk
rm -f miniboot.lss
rm -f miniboot.o I2C-master-lib/i2c_master.o  
rm -f  miniboot.lst I2C-master-lib/i2c_master.lst
rm -f miniboot.s I2C-master-lib/i2c_master.s
rm -f miniboot.d I2C-master-lib/i2c_master.d
rm -f .dep/* 
rm -f bootloader.h
Errors: none
-------- end --------

avr-g++ (GCC) 4.8.1
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

Compiling: miniboot.c
avr-g++ -c -mmcu=atmega328p -I. -g   -Os -pedantic -funsigned-char -funsigned-bitfields -fpack-struct -fshort-enums -Wall -Wstrict-prototypes -Werror -Wa,-adhlns=miniboot.lst  -std=gnu++11 -DF_CPU=8000000UL -MD -MP -MF .dep/miniboot.o.d miniboot.c -o miniboot.o 
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
In file included from miniboot.c:6:0:
bootloader.h:2:1: error: expected unqualified-id before ‘-’ token
 -en 
 ^
Makefile:258: recipe for target 'miniboot.o' failed
make: *** [miniboot.o] Error 1

**Comment by mihaigalos** [comment] 2018-03-22 07:27
can you please list the contents of _your_ bootloader.h?

**Comment by tobiola** [comment] 2018-03-28 23:13
Sorry for the delayed response. 
These are the contents of the bootloader.h file

  1 // Automatically generated by Makefile. DO NOT EDIT!
  2 -en
  3 
  4 #pragma once
  5 -en
  6 
  7 #define BOOTLOADER_START_ADDRESS 0x7800
  8 #define EEPROM_CONFIGURATION_START_BYTE 0x03F6
~

**Comment by mihaigalos** [comment] 2018-03-29 12:38
it looks like the bootloader.h was not correctly generated by make's running of the Makefile. Did you edit the Makefile?

**Comment by lukewaski** [comment] 2018-06-03 08:25
Hello,
got the same exact problem. My bootloader.h looks like obitolas. Havent change anything in the sources.

**Comment by mihaigalos** [comment] 2018-06-03 17:15
Which system are you on? Linux? Are you using make to regenerate the bootloader.h? Does the file get regenerated?

**Comment by lukewaski** [comment] 2018-06-03 17:17
Yes - Im on linux. Tried on raspbian and Debian.
I'm using make rebuild, the bootloader.h file is beeing gerated.


------ Wiadomość oryginalna ------
Od: "Mihai Galos" <notifications@github.com>
Do: "mihaigalos/miniboot" <miniboot@noreply.github.com>
DW: "lukewaski" <admin@3dr.org>; "Comment" <comment@noreply.github.com>
Data: 2018-06-03 19:15:59
Temat: Re: [mihaigalos/miniboot] Error in the generated bootloader file 
made by thet Makefile (#3)

**Comment by mihaigalos** [comment] 2018-06-03 17:21
I have only tested this on windows. I will try to reproduce on raspian when I get home, since I am on holiday now.

In the meantime, if you don't need to modify minibooot, you can use a prebuilt version from /bin.

**Comment by lukewaski** [comment] 2018-06-03 17:21
Thank you!


------ Wiadomość oryginalna ------
Od: "Mihai Galos" <notifications@github.com>
Do: "mihaigalos/miniboot" <miniboot@noreply.github.com>
DW: "lukewaski" <admin@3dr.org>; "Comment" <comment@noreply.github.com>
Data: 2018-06-03 19:21:18
Temat: Re: [mihaigalos/miniboot] Error in the generated bootloader file 
made by thet Makefile (#3)

**Comment by mihaigalos** [comment] 2018-06-10 17:25
Should be fixed with commit 3adcd8327f10ea24103a83207ab5ba7353816667 which was merged into master a few moments ago. Please retest. I will then close this issue.

**Comment by luckwaski** [comment] 2018-06-13 21:06
Thank you - I can confirm it compiles fine under Linux now.

**Closed as completed** 2018-06-14 06:33 UTC
Labels: bug
